"""Claude Code adapter — transpiles neutral skill manifests to .claude/skills/ layout.

Per contract (specs/001-foundation/contracts/runtime-adapter.interface.md):
  - Writes target_dir/.claude/skills/<skill-name>/SKILL.md
  - SKILL.md includes YAML frontmatter with name, description, argument-hint, metadata.source
  - User mode installs into ~/.claude/skills/
  - MUST be idempotent
  - MUST NOT touch files outside .claude/
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Literal

from agent_power_pack.manifest.schema import SkillManifest
from adapters.report import InstallReport


_GENERATED_HEADER = "<!-- GENERATED by agent-power-pack — do not hand-edit -->"


def _render_skill_md(manifest: SkillManifest, manifest_source: str) -> str:
    """Render a SKILL.md file for a single manifest."""
    # Build the trigger hint from the first trigger
    argument_hint = manifest.triggers[0] if manifest.triggers else f"/{manifest.family}:{manifest.name}"

    namespaced = f"{manifest.family}-{manifest.name}"
    lines: list[str] = [
        _GENERATED_HEADER,
        "---",
        f"name: {namespaced}",
        f"description: {manifest.description}",
        f"argument-hint: {argument_hint}",
        "metadata:",
        f"  source: {manifest_source}",
        f"  family: {manifest.family}",
        f"  order: {manifest.order}",
        "---",
        "",
        manifest.prompt,
    ]
    return "\n".join(lines)


class ClaudeAdapter:
    """Transpile neutral manifests into Claude Code's .claude/skills/ layout."""

    runtime_id: Literal["claude-code"] = "claude-code"
    display_name: str = "Claude Code"

    def install(
        self,
        manifests: list[SkillManifest],
        target_dir: Path,
        *,
        mode: Literal["project", "user"] = "project",
    ) -> InstallReport:
        start = time.monotonic()
        report = InstallReport()

        if mode == "user":
            base = Path.home() / ".claude" / "skills"
        else:
            base = target_dir / ".claude" / "skills"

        for manifest in manifests:
            namespaced = f"{manifest.family}-{manifest.name}"
            skill_dir = base / namespaced
            skill_file = skill_dir / "SKILL.md"
            manifest_source = f"manifests/{manifest.family}/{manifest.name}.yaml"

            content = _render_skill_md(manifest, manifest_source)

            skill_dir.mkdir(parents=True, exist_ok=True)

            # Idempotence: skip if content is identical
            if skill_file.exists() and skill_file.read_text() == content:
                report.files_skipped.append(skill_file.relative_to(target_dir if mode == "project" else Path.home()))
                continue

            skill_file.write_text(content)
            report.files_written.append(skill_file.relative_to(target_dir if mode == "project" else Path.home()))

        report.duration_ms = int((time.monotonic() - start) * 1000)
        return report
