"""Codex CLI adapter — transpiles neutral skill manifests to .agents/skills/ layout.

Per contract (specs/001-foundation/contracts/runtime-adapter.interface.md):
  - Writes target_dir/.agents/skills/<skill-name>/SKILL.md
  - SKILL.md includes YAML frontmatter with name, description, triggers, mcp_tools
  - User mode merges MCP server registrations into ~/.codex/config.toml
  - MUST be idempotent
  - MUST NOT touch files outside .agents/ (project) or config.toml (user)
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Literal

from agent_power_pack.manifest.schema import SkillManifest
from adapters.report import InstallReport


_GENERATED_HEADER = "<!-- GENERATED by agent-power-pack — do not hand-edit -->"
_MANAGED_BLOCK_START = "# agent-power-pack managed Codex MCP servers — do not hand-edit"
_MANAGED_BLOCK_END = "# /agent-power-pack managed Codex MCP servers"
_LEGACY_MANAGED_BLOCK_START = "# agent-power-pack managed MCP servers"
_CODEX_STREAMABLE_HTTP_PORTS = {
    "second-opinion": 9100,
    "plane": 9101,
    "wikijs": 9102,
    "nano-banana": 9103,
    "playwright": 9104,
    "playwright-persistent": 9104,
    "woodpecker": 9105,
}


def _render_skill_md(manifest: SkillManifest, manifest_source: str) -> str:
    """Render a SKILL.md file for a single Codex skill."""
    lines: list[str] = [
        _GENERATED_HEADER,
        "---",
        f"name: {manifest.name}",
        f"description: {manifest.description}",
    ]

    # Triggers
    if manifest.triggers:
        lines.append("triggers:")
        for trigger in manifest.triggers:
            lines.append(f"  - {trigger}")

    # MCP tools
    if manifest.mcp_tools:
        lines.append("mcp_tools:")
        for ref in manifest.mcp_tools:
            lines.append(f"  - server: {ref.server}")
            lines.append(f"    tool: {ref.tool}")

    lines.append("metadata:")
    lines.append(f"  source: {manifest_source}")
    lines.append(f"  family: {manifest.family}")
    lines.append(f"  order: {manifest.order}")
    lines.append("---")
    lines.append("")
    lines.append(manifest.prompt)

    return "\n".join(lines)


def _build_mcp_toml_section(manifests: list[SkillManifest]) -> str:
    """Build TOML content for MCP server registrations owned by agent-power-pack.

    Uses the Codex-native ``mcp_servers`` table layout so that
    ``codex mcp list`` can discover the configured servers.
    """
    servers: dict[str, set[str]] = {}
    for m in manifests:
        for ref in m.mcp_tools:
            key = f"agent-power-pack-{ref.server}"
            servers.setdefault(key, set()).add(ref.tool)

    if not servers:
        return ""

    lines: list[str] = [_MANAGED_BLOCK_START]
    for server_key in sorted(servers):
        server_name = server_key.removeprefix("agent-power-pack-")
        port = _CODEX_STREAMABLE_HTTP_PORTS.get(server_name)
        if port is None:
            continue
        lines.append(f'[mcp_servers."{server_key}"]')
        lines.append(f'url = "http://127.0.0.1:{port}"')
        tools = sorted(servers[server_key])
        lines.append(f"# tools = {tools}")
        lines.append("")

    if len(lines) == 1:
        return ""

    lines.append(_MANAGED_BLOCK_END)
    return "\n".join(lines)


def _merge_config_toml(config_path: Path, new_section: str) -> str:
    """Preserve user config while replacing only the managed Codex MCP block."""
    if not new_section.strip():
        return config_path.read_text() if config_path.exists() else ""

    if config_path.exists():
        existing = config_path.read_text()
        managed_ranges = [
            (_MANAGED_BLOCK_START, _MANAGED_BLOCK_END),
            (_LEGACY_MANAGED_BLOCK_START, None),
        ]
        for start_marker, end_marker in managed_ranges:
            start_idx = existing.find(start_marker)
            if start_idx == -1:
                continue
            if end_marker is not None:
                end_idx = existing.find(end_marker, start_idx)
                if end_idx != -1:
                    end_idx += len(end_marker)
                    suffix = existing[end_idx:]
                    if suffix.startswith("\n"):
                        suffix = suffix[1:]
                    return existing[:start_idx] + new_section + "\n" + suffix

            rest = existing[start_idx:]
            lines = rest.split("\n")
            end_offset = len(rest)
            for i, line in enumerate(lines):
                if i == 0:
                    continue
                stripped = line.strip()
                if stripped.startswith("[") and not (
                    stripped.startswith('[mcp_servers."agent-power-pack-')
                    or stripped.startswith('[mcp.servers."agent-power-pack-')
                ):
                    end_offset = sum(len(line) + 1 for line in lines[:i])
                    break
            return existing[:start_idx] + new_section + "\n" + existing[start_idx + end_offset:]

        separator = "\n" if existing.endswith("\n") else "\n\n"
        return existing + separator + new_section + "\n"

    return new_section + "\n"


class CodexAdapter:
    """Transpile neutral manifests into Codex CLI's .agents/skills/ layout."""

    runtime_id: Literal["codex-cli"] = "codex-cli"
    display_name: str = "Codex CLI"

    def install(
        self,
        manifests: list[SkillManifest],
        target_dir: Path,
        *,
        mode: Literal["project", "user"] = "project",
    ) -> InstallReport:
        start = time.monotonic()
        report = InstallReport()

        if mode == "user":
            base = Path.home() / ".agents" / "skills"
        else:
            base = target_dir / ".agents" / "skills"

        for manifest in manifests:
            skill_dir = base / manifest.name
            skill_file = skill_dir / "SKILL.md"
            manifest_source = f"manifests/{manifest.family}/{manifest.name}.yaml"

            content = _render_skill_md(manifest, manifest_source)

            skill_dir.mkdir(parents=True, exist_ok=True)

            # Idempotence: skip if content is identical
            if skill_file.exists() and skill_file.read_text() == content:
                report.files_skipped.append(skill_file.relative_to(target_dir if mode == "project" else Path.home()))
                continue

            skill_file.write_text(content)
            report.files_written.append(skill_file.relative_to(target_dir if mode == "project" else Path.home()))

        # User mode: merge MCP config into ~/.codex/config.toml
        if mode == "user":
            config_path = Path.home() / ".codex" / "config.toml"
            new_section = _build_mcp_toml_section(manifests)
            if new_section:
                merged = _merge_config_toml(config_path, new_section)
                if not config_path.exists() or config_path.read_text() != merged:
                    config_path.parent.mkdir(parents=True, exist_ok=True)
                    config_path.write_text(merged)
                    report.files_written.append(config_path.relative_to(Path.home()))
                else:
                    report.files_skipped.append(config_path.relative_to(Path.home()))

        report.duration_ms = int((time.monotonic() - start) * 1000)
        return report
