"""Codex CLI adapter — transpiles neutral skill manifests to .codex/ layout.

Per contract (specs/001-foundation/contracts/runtime-adapter.interface.md):
  - Writes target_dir/.codex/skills/<skill-name>/agents/openai.yaml
  - Writes target_dir/.codex/prompts/<family>/<skill-name>.md
  - User mode merges MCP server registrations into ~/.codex/config.toml
  - MUST be idempotent
  - MUST NOT touch files outside .codex/
"""

from __future__ import annotations

import time
from pathlib import Path
from typing import Literal

from ruamel.yaml import YAML

from agent_power_pack.manifest.schema import SkillManifest
from adapters.report import InstallReport


_GENERATED_HEADER = "<!-- GENERATED by agent-power-pack — do not hand-edit -->"


def _make_yaml() -> YAML:
    yaml = YAML(typ="rt")
    yaml.preserve_quotes = True
    yaml.default_flow_style = False
    yaml.width = 120
    return yaml


def _render_openai_yaml(manifest: SkillManifest) -> dict:
    """Build the openai.yaml agent definition for Codex CLI."""
    return {
        "name": manifest.name,
        "family": manifest.family,
        "description": manifest.description,
        "triggers": manifest.triggers,
        "mcp_tools": [
            {"server": ref.server, "tool": ref.tool}
            for ref in manifest.mcp_tools
        ],
    }


def _render_prompt_md(manifest: SkillManifest) -> str:
    """Render the prompt entrypoint markdown for Codex CLI."""
    lines: list[str] = [
        _GENERATED_HEADER,
        f"# {manifest.triggers[0] if manifest.triggers else manifest.name}",
        "",
        manifest.prompt,
    ]
    return "\n".join(lines)


def _build_mcp_toml_section(manifests: list[SkillManifest]) -> str:
    """Build TOML content for MCP server registrations owned by agent-power-pack."""
    servers: dict[str, set[str]] = {}
    for m in manifests:
        for ref in m.mcp_tools:
            key = f"agent-power-pack-{ref.server}"
            servers.setdefault(key, set()).add(ref.tool)

    if not servers:
        return ""

    lines: list[str] = [
        "# agent-power-pack managed MCP servers — do not hand-edit this section",
    ]
    for server_key in sorted(servers):
        lines.append(f'[mcp.servers."{server_key}"]')
        tools = sorted(servers[server_key])
        lines.append(f"tools = {tools}")
        lines.append("")

    return "\n".join(lines)


def _merge_config_toml(config_path: Path, new_section: str) -> str:
    """Conservative three-way merge: preserve existing sections, update only our sections."""
    if not new_section.strip():
        return config_path.read_text() if config_path.exists() else ""

    marker_start = "# agent-power-pack managed MCP servers"
    if config_path.exists():
        existing = config_path.read_text()
        # Find and replace our managed section
        start_idx = existing.find(marker_start)
        if start_idx != -1:
            # Find the end of our section (next non-mcp section or EOF)
            rest = existing[start_idx:]
            # Our section ends at the next line that starts a non-mcp section header
            lines = rest.split("\n")
            end_offset = len(rest)
            for i, line in enumerate(lines):
                if i == 0:
                    continue
                stripped = line.strip()
                # A new top-level section that isn't ours
                if stripped.startswith("[") and not stripped.startswith('[mcp.servers."agent-power-pack-'):
                    end_offset = sum(len(line) + 1 for line in lines[:i])
                    break
            return existing[:start_idx] + new_section + "\n" + existing[start_idx + end_offset:]
        else:
            # Append our section
            separator = "\n" if existing.endswith("\n") else "\n\n"
            return existing + separator + new_section + "\n"
    else:
        return new_section + "\n"


class CodexAdapter:
    """Transpile neutral manifests into Codex CLI's .codex/ layout."""

    runtime_id: Literal["codex-cli"] = "codex-cli"
    display_name: str = "Codex CLI"

    def install(
        self,
        manifests: list[SkillManifest],
        target_dir: Path,
        *,
        mode: Literal["project", "user"] = "project",
    ) -> InstallReport:
        start = time.monotonic()
        report = InstallReport()
        yaml = _make_yaml()

        if mode == "user":
            base = Path.home() / ".codex"
        else:
            base = target_dir / ".codex"

        for manifest in manifests:
            # 1. Write agents/openai.yaml
            agent_dir = base / "skills" / manifest.name / "agents"
            agent_file = agent_dir / "openai.yaml"
            agent_data = _render_openai_yaml(manifest)

            agent_dir.mkdir(parents=True, exist_ok=True)

            import io
            buf = io.StringIO()
            yaml.dump(agent_data, buf)
            agent_content = buf.getvalue()

            if agent_file.exists() and agent_file.read_text() == agent_content:
                report.files_skipped.append(agent_file.relative_to(target_dir if mode == "project" else Path.home()))
            else:
                agent_file.write_text(agent_content)
                report.files_written.append(agent_file.relative_to(target_dir if mode == "project" else Path.home()))

            # 2. Write prompts/<family>/<name>.md
            prompt_dir = base / "prompts" / manifest.family
            prompt_file = prompt_dir / f"{manifest.name}.md"
            prompt_content = _render_prompt_md(manifest)

            prompt_dir.mkdir(parents=True, exist_ok=True)

            if prompt_file.exists() and prompt_file.read_text() == prompt_content:
                report.files_skipped.append(prompt_file.relative_to(target_dir if mode == "project" else Path.home()))
            else:
                prompt_file.write_text(prompt_content)
                report.files_written.append(prompt_file.relative_to(target_dir if mode == "project" else Path.home()))

        # 3. User mode: merge MCP config into ~/.codex/config.toml
        if mode == "user":
            config_path = Path.home() / ".codex" / "config.toml"
            new_section = _build_mcp_toml_section(manifests)
            if new_section:
                merged = _merge_config_toml(config_path, new_section)
                if not config_path.exists() or config_path.read_text() != merged:
                    config_path.parent.mkdir(parents=True, exist_ok=True)
                    config_path.write_text(merged)
                    report.files_written.append(config_path.relative_to(Path.home()))
                else:
                    report.files_skipped.append(config_path.relative_to(Path.home()))

        report.duration_ms = int((time.monotonic() - start) * 1000)
        return report
