"""Plan generation for docs:analyze (spec 002, FR-003).

Assembles docs/plan.yaml from signal detection results and theme analysis.
Preserves existing plan metadata when merging.
"""

from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Any

import structlog
from ruamel.yaml import YAML

from agent_power_pack.docs.signal_detector import ArtifactProposal

logger = structlog.get_logger()


def generate_plan(
    project_name: str,
    proposals: list[ArtifactProposal],
    plan_path: Path,
    convention_path: str = "docs/wiki-structure.yaml",
) -> dict[str, Any]:
    """Generate or update docs/plan.yaml with artifact proposals.

    If plan.yaml already exists, preserves project/convention metadata
    and merges new artifacts (does not overwrite manual edits to existing
    artifact entries).
    """
    yaml = YAML()
    yaml.default_flow_style = False

    existing: dict[str, Any] = {}
    if plan_path.exists():
        with open(plan_path) as f:
            loaded = yaml.load(f)
            if loaded:
                existing = dict(loaded)

    # Preserve existing metadata
    plan: dict[str, Any] = {
        "project": existing.get("project", project_name),
        "convention": existing.get("convention", convention_path),
        "artifacts": [],
    }

    # Build a map of existing artifacts by type for merge logic
    existing_artifacts: dict[str, dict[str, Any]] = {}
    for art in existing.get("artifacts", []):
        if isinstance(art, dict) and "type" in art:
            existing_artifacts[art["type"]] = art

    # Merge proposals with existing artifacts
    for proposal in proposals:
        if proposal.type in existing_artifacts:
            # Preserve manual edits — only update source_signals and confidence
            merged = dict(existing_artifacts[proposal.type])
            merged["source_signals"] = proposal.source_signals
            merged["confidence"] = proposal.confidence
            plan["artifacts"].append(merged)
        else:
            plan["artifacts"].append(asdict(proposal))

    # Keep any existing artifacts not in proposals (user-added custom types)
    proposed_types = {p.type for p in proposals}
    for art_type, art_data in existing_artifacts.items():
        if art_type not in proposed_types:
            plan["artifacts"].append(art_data)

    return plan


def write_plan_yaml(plan: dict[str, Any], plan_path: Path) -> None:
    """Write the documentation plan to a YAML file."""
    yaml = YAML()
    yaml.default_flow_style = False

    plan_path.parent.mkdir(parents=True, exist_ok=True)

    with open(plan_path, "w") as f:
        f.write("# Documentation plan — generated by docs:analyze (spec 002, FR-003).\n")
        f.write("# Edit freely; docs:auto respects your changes.\n")
        f.write("# Remove artifacts you don't want; add custom ones with type: custom.\n")
        f.write("\n")
        yaml.dump(plan, f)
